### PR TITLE
Fix/#544 fix window history

### LINKED ISSUE #544: Fix window history
Fix window history on projects, proposals and voting page

### PR DESCRIPTION
**Pull request by Zuckerwattederivat**
Fixes #544

### CODE REVIEW

**Comment by Zuckerwattederivat** [comment]
Seemingly fixed in vue-router v4. This workaround can be discarded when we update.

File: components/layout/AppMobileNavbar.vue [hunk 1]
```diff
@@ -18,22 +18,24 @@
             }}</NuxtLink>
           </li>
           <li>
-            <NuxtLink class="font-bold block px-4 py-3" to="/projects?first">{{
-              $t('navbar.navbarProjects')
-            }}</NuxtLink>
+            <span
```
Comment (KinimodEtlon) [inline components/layout/AppMobileNavbar.vue:21]: nitpick(blocking): since the redirect is now an click we can loose the span div and use the li element directly, same for the other ones

File: components/layout/AppMobileNavbar.vue [hunk 2]
```diff
@@ -118,6 +121,9 @@ export default {
       this.$store.commit('alert/clear');
       context.toggleOpen();
     },
+    to(route) {
+      sameRouteReload(this, route, 'in');
```
Comment (KinimodEtlon) [inline components/layout/AppMobileNavbar.vue:125]: nitpick(blocking): 'in' is the default value for this param so you should leave it out here. Or, you could make this param null, i guess this function might be used in some other places as well.

File: helpers/windowHistory.ts [hunk 3]
```diff
@@ -1,19 +1,34 @@
...
+    query,
+  });
+}
+
+export function sameRouteReload(
+  _this: Record<string, any>,
+  route: string,
+  queryHook: string = 'in',
+): void {
+  if (_this.$route.path !== route) {
```
Comment (KinimodEtlon) [inline helpers/windowHistory.ts:18]: nitpick(non-blocking): is this really the only way to do this? The 'in' will be displayed in the url shortly and then we have an immediate redirect.

**Review by KinimodEtlon — CHANGES_REQUESTED** [review]

File: helpers/windowHistory.ts (hunk 3 above)
Comment (Zuckerwattederivat) [reply helpers/windowHistory.ts:18]: I'll do some more research today. Otherwise if I can't find another way to do this, the alternatives are:

- keep this workaround until we upgraded to vue-router v4
- ditch same page reload via navbar altogether as is the standard behavior in the current router version

File: components/layout/AppMobileNavbar.vue (hunk 1 above)
Comment (Zuckerwattederivat) [reply components/layout/AppMobileNavbar.vue:21]: Good point

File: components/layout/AppMobileNavbar.vue (hunk 2 above)
Comment (Zuckerwattederivat) [reply components/layout/AppMobileNavbar.vue:125]: Good point. I completely forgot that I set this as a default.

File: components/layout/AppMobileNavbar.vue [hunk 4]
```diff
@@ -17,23 +17,26 @@
...
+            <app-link to="/dao-voting" store-name="dao-voting-filter">{{
+              $t('leaderboard.meta.title')
+            }}</app-link>
           </li>
           <li>
-            <NuxtLink
-              class="font-bold block px-4 py-3"
-              to="/dao-voting?current"
-              >{{ $t('leaderboard.meta.title') }}</NuxtLink
+            <span
```
Comment (KinimodEtlon) [inline components/layout/AppMobileNavbar.vue:36]: question(blocking): Why is this one different than the others? Shouldn't this div also be an app-link?

File: components/layout/AppMobileNavbar.vue [hunk 5]
```diff
@@ -118,6 +123,9 @@ export default {
       this.$store.commit('alert/clear');
       context.toggleOpen();
     },
+    to(route) {
```
Comment (KinimodEtlon) [inline components/layout/AppMobileNavbar.vue:126]: task(blocking): if the div is an app-link component this function would be obsolete, also, i was unable to find the helper function for sameRouteReload. This would cause a js error if the link is clicked, please remove it.

**Review by KinimodEtlon — CHANGES_REQUESTED** [review]

File: components/layout/AppMobileNavbar.vue (hunk 4 above)
Comment (Zuckerwattederivat) [reply components/layout/AppMobileNavbar.vue]: Fixed

File: components/layout/AppMobileNavbar.vue (hunk 5 above)
Comment (Zuckerwattederivat) [reply components/layout/AppMobileNavbar.vue]: Fixed

**Comment by marhali** [comment]
Blocking by new navbar #581

**Review by KinimodEtlon — APPROVED** [review]
