### PR TITLE
Feat/698 misc bugs

### LINKED ISSUE #698: New theme bugs
Redirect hint
image

Image Preview
image

### PR DESCRIPTION
**Pull request by marhali**
Resolves #698

### CODE REVIEW

File: components/common/AppImageModal.vue [hunk 1]
```diff
@@ -56,26 +45,54 @@ export default {
...
+
+  methods: {
+    backdropClose(e) {
+      if (e.target.classList.contains('modal-backdrop')) this.$emit('close');
+    },
+  },
+};
 </script>
 
-<style scoped>
```
Comment (Abrom8) [inline components/common/AppImageModal.vue:73]: suggestion(blocking): add scoped again

**Review by Abrom8 — APPROVED** [review]
